### ISSUE TITLE
How get background color like in Sublime Text

### ISSUE THREAD

**Issue by OlegLoewen** [BroFox86/espresso-soda#1]
How get text background color like in Sublime Text?
And how to set the font-weight?

![image](https://user-images.githubusercontent.com/44769983/54685996-80941f00-4b18-11e9-8424-2622e55f49ae.png)

**Comment by BroFox86** [comment]
VSC does not support background declarations of the rules. At least it did not support it during my last update of the theme six months ago.

**Comment by OlegLoewen** [comment]
Okay, too bad. Thanks for a quick reply.
What about the font weight? I use the same font in both editors (Menlo). But in Sublime Text (left) it seems a little bit bolder, than in VS Code (right), although both are using Menlo regular font. Do you have an idea I can get the font on VS Code to look the same way as in Sublime Text?

**Comment by BroFox86** [comment]
Sorry for the late answer. In your settings.json add this line: "editor.fontWeight": "bold"

![Снимок экрана 2019-03-22 в 8 54 59](https://user-images.githubusercontent.com/23554264/54803435-87d63c80-4c80-11e9-8237-70a755ab5169.png)

**Comment by BroFox86** [comment]
Update. 

Now you can adjust font-weight by `editor.fontWeight`. Example: `"editor.fontWeight": 500`.

<img width="400" alt="Снимок экрана 2021-10-02 в 19 28 23" src="https://user-images.githubusercontent.com/23554264/135724907-a8e1c908-08ee-4d8e-b5cf-858a821d67ad.png">
