### ISSUE TITLE
Updated activity bar color

### ISSUE THREAD

**Issue by brtdv** [BroFox86/espresso-soda#3]
Hi @BroFox86,

Would you be open for a pull request that updates the black background color of the Activity Bar to a (light) color that matches the general light aesthetic of the Espresso-soda theme? 

I would implement this, and make sure activity bar has a color that matches the original UI of the [Espresso editor](https://www.espressoapp.com), the app from which this theme was ported.

If yes, I would like to submit a pull request with a change like that. 
Let me know,
Cheers.,
B.

**Comment by brtdv** [comment]
See also this screenshot: <img width="1189" alt="Screenshot 2021-10-01 at 14 04 54" src="https://user-images.githubusercontent.com/932365/135617043-c26f5236-dd8f-4c17-b833-e17bb609e6e6.png">

**Comment by BroFox86** [comment]
Hi @brtdv. 

Yes, you can do a pull request for this. Please attach a screenshot of the updated bar after that. 

Thanks for participating.
