### ISSUE TITLE
Scrollbar background same as side panel background renders explorer scrollbar not visible

### ISSUE THREAD

**Issue by alkuzad** [BroFox86/espresso-soda#5]
I fixed it with:

```
"workbench.colorCustomizations":{
    "scrollbarSlider.background": "#A5A6AC",
    "scrollbarSlider.hoverBackground": "#A5A6AC",
},
```
to make scrollbars darker, impacts all scrollbars, not only sidebar

**Comment by BroFox86** [comment]
Updated: https://github.com/BroFox86/espresso-soda/commit/e2e1f722534f2a8949afa660a732886f3c3d7cdf

I used scrollbar color from Espresso editor. Thank you for participating.

<img width="500" alt="Screenshot" src="https://user-images.githubusercontent.com/23554264/140556997-b0eaaa95-4ec9-4427-bab2-dc92afc0fc1d.png">
